<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;
use App\Models\Province;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        // خريطة province_name_ar → id
        $prov = Province::pluck('id', 'name_ar');

        $hotels = [
            [
                'name'           => 'فندق فور سيزونز دمشق',
                'city'           => 'دمشق',
                'province_id'    => $prov['دمشق'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 290,
                'discount_price' => 260,
                'rating'         => 4.8,
                'rooms'          => 80,
                'status'         => 'active',
                'tag'            => 'فاخر',
                'image_url'      => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مسبح خارجي', 'سبا فاخر', 'واي فاي مجاني', 'موقف سيارات', 'فطور ملكي'],
                'offer_text'     => 'خصم 10% للحجوزات المبكرة هذا الأسبوع!',
                'description'    => 'فندق عالمي فاخر في قلب دمشق يوفر أرقى مستويات الضيافة.',
            ],
            [
                'name'           => 'فندق بيت الوالي التراثي',
                'city'           => 'دمشق',
                'province_id'    => $prov['دمشق'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 250,
                'discount_price' => null,
                'rating'         => 4.9,
                'rooms'          => 20,
                'status'         => 'active',
                'tag'            => 'تراثي',
                'image_url'      => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['طراز دمشقي قديم', 'فطور شرقي متكامل', 'ساحة سماوية', 'واي فاي سريع'],
                'offer_text'     => 'عشاء دمشقي مجاني عند حجز ليلتين أو أكثر',
                'description'    => 'بيت دمشقي أثري مُحوَّل إلى فندق بوتيكي فريد من نوعه.',
            ],
            [
                'name'           => 'فندق داما روز',
                'city'           => 'دمشق',
                'province_id'    => $prov['دمشق'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 180,
                'discount_price' => 165,
                'rating'         => 4.4,
                'rooms'          => 60,
                'status'         => 'active',
                'tag'            => 'أعمال',
                'image_url'      => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['موقع حيوي مركز المدينة', 'قاعات مؤتمرات', 'مسبح', 'نادي رياضي'],
                'offer_text'     => 'عرض خاص لرجال الأعمال والشركات',
                'description'    => 'فندق حديث في موقع استراتيجي يناسب رجال الأعمال والزوار.',
            ],
            [
                'name'           => 'فندق شيراتون دمشق',
                'city'           => 'دمشق',
                'province_id'    => $prov['دمشق'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 240,
                'discount_price' => null,
                'rating'         => 4.5,
                'rooms'          => 100,
                'status'         => 'active',
                'tag'            => 'فاخر',
                'image_url'      => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['حدائق واسعة', 'مسابح متعددة', 'مطاعم عالمية', 'مواقف مؤمنة'],
                'offer_text'     => null,
                'description'    => 'سلسلة شيراتون العالمية بخدماتها المتميزة في دمشق.',
            ],
            [
                'name'           => 'فندق بيت المملوكة دمشق القديمة',
                'city'           => 'دمشق',
                'province_id'    => $prov['دمشق'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 120,
                'discount_price' => 100,
                'rating'         => 4.9,
                'rooms'          => 12,
                'status'         => 'active',
                'tag'            => 'تراثي',
                'image_url'      => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['فناء دمشقي أثري', 'بحرة ماء', 'فطور شرقي تقليدي', 'تكييف كامل', 'موقع تاريخي'],
                'offer_text'     => 'فندق تراثي بوتيكي بتجربة دمشقية أصيلة',
                'description'    => 'فندق بوتيكي داخل بيت دمشقي مملوكي تاريخي.',
            ],
            [
                'name'           => 'فندق بلودان الكبير',
                'city'           => 'يبرود',
                'province_id'    => $prov['ريف دمشق'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 95,
                'discount_price' => null,
                'rating'         => 4.3,
                'rooms'          => 40,
                'status'         => 'active',
                'tag'            => 'جبلي',
                'image_url'      => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['إطلالة جبلية ساحرة', 'طقس بارد صيفاً', 'تراس خارجي', 'مطعم جبلي'],
                'offer_text'     => 'خصم عائلي مميز في عطلة نهاية الأسبوع',
                'description'    => 'منتجع جبلي رائع بإطلالات خلابة على بلودان.',
            ],
            [
                'name'           => 'فندق سفير حمص',
                'city'           => 'حمص',
                'province_id'    => $prov['حمص'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 180,
                'discount_price' => null,
                'rating'         => 4.6,
                'rooms'          => 55,
                'status'         => 'active',
                'tag'            => 'فاخر',
                'image_url'      => 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مسبح مكشوف', 'مطعم بجانب المسبح', 'حدائق هادئة'],
                'offer_text'     => 'دخول مجاني للنادي الرياضي طوال فترة الإقامة',
                'description'    => 'الفندق الأفضل في حمص بخدمات فندقية متكاملة.',
            ],
            [
                'name'           => 'فندق الوادي السياحي حمص',
                'city'           => 'حمص',
                'province_id'    => $prov['حمص'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 100,
                'discount_price' => 85,
                'rating'         => 4.5,
                'rooms'          => 30,
                'status'         => 'active',
                'tag'            => 'سياحي',
                'image_url'      => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['إطلالة على قلعة الحصن', 'تراس عائلي', 'ألعاب أطفال', 'تنظيم رحلات'],
                'offer_text'     => null,
                'description'    => 'فندق سياحي قريب من قلعة الحصن الأثرية.',
            ],
            [
                'name'           => 'فندق أفاميا الشام حماة',
                'city'           => 'حماة',
                'province_id'    => $prov['حماة'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 130,
                'discount_price' => null,
                'rating'         => 4.3,
                'rooms'          => 45,
                'status'         => 'active',
                'tag'            => 'سياحي',
                'image_url'      => 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مطل على نهر العاصي والنواعير', 'حدائق خلابة', 'مطعم شرقي وغربي'],
                'offer_text'     => null,
                'description'    => 'فندق فاخر بإطلالة على نهر العاصي ونواعير حماة التاريخية.',
            ],
            [
                'name'           => 'فندق شهباء حلب',
                'city'           => 'حلب',
                'province_id'    => $prov['حلب'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 145,
                'discount_price' => 130,
                'rating'         => 4.2,
                'rooms'          => 65,
                'status'         => 'active',
                'tag'            => 'أعمال',
                'image_url'      => 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مسبح كبير', 'مركز رجال أعمال', 'صالة لياقة بدنية'],
                'offer_text'     => 'شامل الفطور والإنترنت السريع مجاناً',
                'description'    => 'فندق فاخر في حلب يناسب الأعمال والسياحة.',
            ],
            [
                'name'           => 'فندق ريجا بالاس حلب',
                'city'           => 'حلب',
                'province_id'    => $prov['حلب'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 90,
                'discount_price' => null,
                'rating'         => 4.0,
                'rooms'          => 35,
                'status'         => 'active',
                'tag'            => 'اقتصادي',
                'image_url'      => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['قريب من الخدمات', 'غرف عائلية مريحة', 'مطعم بانورامي'],
                'offer_text'     => null,
                'description'    => 'فندق اقتصادي مريح في موقع مركزي بحلب.',
            ],
            [
                'name'           => 'فندق شيراتون حلب',
                'city'           => 'حلب',
                'province_id'    => $prov['حلب'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 145,
                'discount_price' => 130,
                'rating'         => 4.6,
                'rooms'          => 70,
                'status'         => 'active',
                'tag'            => 'فاخر',
                'image_url'      => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مركز لرجال الأعمال', 'قاعة اجتماعات', 'مطعم حلبي تراثي', 'توصيل مطار'],
                'offer_text'     => null,
                'description'    => 'فندق شيراتون الشهير بخدماته العالمية في مدينة حلب.',
            ],
            [
                'name'           => 'منتجع أفاميا ريزورت اللاذقية',
                'city'           => 'اللاذقية',
                'province_id'    => $prov['اللاذقية'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 210,
                'discount_price' => 190,
                'rating'         => 4.6,
                'rooms'          => 90,
                'status'         => 'active',
                'tag'            => 'بحري',
                'image_url'      => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['شاليهات تطل على البحر', 'مسابح خارجية', 'واي فاي مجاني', 'ملاعب تنس'],
                'offer_text'     => 'شامل الفطور بوفيه مفتوح لشخصين مجاناً',
                'description'    => 'منتجع ساحلي فاخر على شاطئ اللاذقية.',
            ],
            [
                'name'           => 'منتجع أفاميا الشام اللاذقية',
                'city'           => 'اللاذقية',
                'province_id'    => $prov['اللاذقية'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 210,
                'discount_price' => 180,
                'rating'         => 4.9,
                'rooms'          => 75,
                'status'         => 'active',
                'tag'            => 'بحري',
                'image_url'      => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['شاطئ خاص', 'مسبح عائلي', 'ألعاب مائية', 'عدة مطاعم', 'إطلالة بحرية'],
                'offer_text'     => 'منتجع متكامل بخدمات عالمية',
                'description'    => 'منتجع شامل الخدمات مع شاطئ خاص على البحر المتوسط.',
            ],
            [
                'name'           => 'فندق قصر اللاذقية',
                'city'           => 'اللاذقية',
                'province_id'    => $prov['اللاذقية'] ?? null,
                'stars'          => 3,
                'price_per_night'=> 45,
                'discount_price' => null,
                'rating'         => 4.0,
                'rooms'          => 25,
                'status'         => 'active',
                'tag'            => 'اقتصادي',
                'image_url'      => 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['اقتصادي ومريح', 'قريب من الخدمات', 'طاقم عمل ودود'],
                'offer_text'     => null,
                'description'    => 'فندق اقتصادي مريح لأصحاب الميزانية المحدودة.',
            ],
            [
                'name'           => 'منتجع جونادا السياحي طرطوس',
                'city'           => 'طرطوس',
                'province_id'    => $prov['طرطوس'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 160,
                'discount_price' => 145,
                'rating'         => 4.9,
                'rooms'          => 85,
                'status'         => 'active',
                'tag'            => 'بحري',
                'image_url'      => 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['شاطئ رملي خاص', 'Aqua Park', 'تراس بحري', 'عدة مطاعم'],
                'offer_text'     => 'احجز ليلة واحصل على الثانية بنصف السعر خلال هذا الشهر!',
                'description'    => 'المنتجع الأشهر في طرطوس بشاطئ خاص وألعاب مائية.',
            ],
            [
                'name'           => 'فندق شاهين كورنيش طرطوس',
                'city'           => 'طرطوس',
                'province_id'    => $prov['طرطوس'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 90,
                'discount_price' => null,
                'rating'         => 4.1,
                'rooms'          => 28,
                'status'         => 'active',
                'tag'            => 'بحري',
                'image_url'      => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['إطلالة على البحر والجزيرة', 'قريب من المقاهي والأسواق'],
                'offer_text'     => null,
                'description'    => 'فندق على الكورنيش بإطلالة مباشرة على البحر.',
            ],
            [
                'name'           => 'منتجع بلو باي طرطوس',
                'city'           => 'طرطوس',
                'province_id'    => $prov['طرطوس'] ?? null,
                'stars'          => 5,
                'price_per_night'=> 175,
                'discount_price' => 155,
                'rating'         => 4.8,
                'rooms'          => 50,
                'status'         => 'active',
                'tag'            => 'بحري',
                'image_url'      => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['مسبح خارجي', 'شاليهات خاصة', 'منطقة ألعاب أطفال', 'جلسات عالبحر'],
                'offer_text'     => 'إقامة عائلية بأسعار خاصة',
                'description'    => 'منتجع عائلي فاخر مع شاليهات خاصة.',
            ],
            [
                'name'           => 'فندق بادية الشام دير الزور',
                'city'           => 'دير الزور',
                'province_id'    => $prov['دير الزور'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 132,
                'discount_price' => null,
                'rating'         => 4.2,
                'rooms'          => 38,
                'status'         => 'active',
                'tag'            => 'سياحي',
                'image_url'      => 'https://images.unsplash.com/photo-1554009975-d74653b879f1?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['قريب من نهر الفرات', 'قاعات واسعة للمناسبات', 'مطعم شرقي أصيل'],
                'offer_text'     => null,
                'description'    => 'فندق على ضفاف نهر الفرات بأجواء شرقية أصيلة.',
            ],
            [
                'name'           => 'فندق القامشلي سنتر',
                'city'           => 'القامشلي',
                'province_id'    => $prov['الحسكة'] ?? null,
                'stars'          => 4,
                'price_per_night'=> 110,
                'discount_price' => null,
                'rating'         => 4.1,
                'rooms'          => 32,
                'status'         => 'active',
                'tag'            => 'عمل',
                'image_url'      => 'https://images.unsplash.com/photo-1606046604972-77cc76aee944?auto=format&fit=crop&w=800&q=80',
                'amenities'      => ['إنترنت سريع ومستقر', 'خدمة غرف 24 ساعة', 'موقع هادئ'],
                'offer_text'     => null,
                'description'    => 'فندق حديث في القامشلي بخدمات متكاملة.',
            ],
        ];

        foreach ($hotels as $hotel) {
            Hotel::firstOrCreate(
                ['name' => $hotel['name'], 'city' => $hotel['city']],
                $hotel
            );
        }
    }
}
