<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;
use App\Models\Province;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        $prov = Province::pluck('id', 'name_ar');

        $hotels = [

            // ── دمشق ─────────────────────────────────────────────────────────
            [
                'name'            => 'Four Seasons Hotel Damascus',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 5,
                'price_per_night' => 290,
                'discount_price'  => 260,
                'rating'          => 4.8,
                'rooms'           => 80,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مسبح خارجي', 'سبا فاخر', 'واي فاي مجاني', 'موقف سيارات', 'فطور ملكي'],
                'offer_text'      => 'خصم 10% للحجوزات المبكرة',
                'description'     => 'فندق عالمي فاخر في قلب دمشق. للاطلاع على الصور: https://www.google.com/maps/search/?api=1&query=Four+Seasons+Hotel+Damascus',
            ],
            [
                'name'            => 'Beit Zafran Hotel De Charme',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 130,
                'discount_price'  => null,
                'rating'          => 4.7,
                'rooms'           => 15,
                'status'          => 'active',
                'tag'             => 'تراثي',
                'image_url'       => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['طراز دمشقي قديم', 'فناء داخلي', 'فطور شرقي', 'واي فاي'],
                'offer_text'      => 'تجربة دمشقية أصيلة',
                'description'     => 'بيت دمشقي تراثي مُحوَّل إلى فندق بوتيكي. صور: https://www.tripadvisor.com/Search?q=Beit+Zafran+Hotel+De+Charme',
            ],
            [
                'name'            => 'Cham Palace Hotel',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 5,
                'price_per_night' => 220,
                'discount_price'  => 200,
                'rating'          => 4.5,
                'rooms'           => 100,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مسبح', 'قاعات مؤتمرات', 'مطاعم متعددة', 'موقف'],
                'offer_text'      => null,
                'description'     => 'فندق شام بالاس الشهير في دمشق. هاتف: +963112232300',
            ],
            [
                'name'            => 'Beit Al Wali Hotel',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 150,
                'discount_price'  => null,
                'rating'          => 4.8,
                'rooms'           => 18,
                'status'          => 'active',
                'tag'             => 'تراثي',
                'image_url'       => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['باب توما', 'ساحة سماوية', 'فطور دمشقي', 'واي فاي'],
                'offer_text'      => 'في قلب الحي المسيحي',
                'description'     => 'بيت الوالي في باب توما. هاتف: +963115436666',
            ],
            [
                'name'            => 'Dama Rose Hotel',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 180,
                'discount_price'  => 165,
                'rating'          => 4.4,
                'rooms'           => 60,
                'status'          => 'active',
                'tag'             => 'أعمال',
                'image_url'       => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مركزي', 'قاعات مؤتمرات', 'مسبح', 'نادي رياضي'],
                'offer_text'      => 'عرض خاص لرجال الأعمال',
                'description'     => 'فندق داما روز في شارع شكري القوتلي. هاتف: +963112229200',
            ],
            [
                'name'            => 'Beit al-Mamlouka',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 5,
                'price_per_night' => 200,
                'discount_price'  => null,
                'rating'          => 4.9,
                'rooms'           => 12,
                'status'          => 'active',
                'tag'             => 'تراثي',
                'image_url'       => 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['بيت مملوكي أثري', 'بحرة ماء', 'فطور تقليدي', 'تكييف'],
                'offer_text'      => 'أحد أجمل البيوت الدمشقية',
                'description'     => 'بيت المملوكة في جادة البكري. هاتف: +963115430445',
            ],
            [
                'name'            => 'Sheraton Damascus Hotel',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 5,
                'price_per_night' => 240,
                'discount_price'  => null,
                'rating'          => 4.5,
                'rooms'           => 100,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['حدائق واسعة', 'مسابح متعددة', 'مطاعم عالمية', 'سبا'],
                'offer_text'      => null,
                'description'     => 'شيراتون دمشق في شارع شكري القوتلي.',
            ],
            [
                'name'            => 'Omayad Hotel Damascus',
                'city'            => 'دمشق',
                'province_id'     => $prov['دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 120,
                'discount_price'  => 105,
                'rating'          => 4.2,
                'rooms'           => 45,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1554009975-d74653b879f1?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مركزي', 'مطعم', 'واي فاي', 'موقف سيارات'],
                'offer_text'      => null,
                'description'     => 'فندق أموية في تقاطع شارع ميسلون. هاتف: +963112217700',
            ],

            // ── ريف دمشق ──────────────────────────────────────────────────────
            [
                'name'            => 'Bloudan Grand Hotel',
                'city'            => 'بلودان',
                'province_id'     => $prov['ريف دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 95,
                'discount_price'  => null,
                'rating'          => 4.3,
                'rooms'           => 40,
                'status'          => 'active',
                'tag'             => 'جبلي',
                'image_url'       => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['إطلالة جبلية', 'هواء نقي', 'تراس خارجي', 'مطعم جبلي'],
                'offer_text'      => 'خصم عائلي في عطلة نهاية الأسبوع',
                'description'     => 'فندق كبير في بلودان الجبلية. هاتف: +963117160070',
            ],
            [
                'name'            => 'Sheraton Ma\'aret Sednaya Hotel & Resort',
                'city'            => 'صيدنايا',
                'province_id'     => $prov['ريف دمشق'] ?? null,
                'stars'           => 5,
                'price_per_night' => 185,
                'discount_price'  => 165,
                'rating'          => 4.6,
                'rooms'           => 65,
                'status'          => 'active',
                'tag'             => 'منتجع',
                'image_url'       => 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مسبح', 'إطلالة جبلية', 'قريب من صيدنايا', 'سبا', 'مطعم'],
                'offer_text'      => 'منتجع شيراتون الجبلي',
                'description'     => 'شيراتون معرة صيدنايا. هاتف: +963115958000',
            ],
            [
                'name'            => 'Yafour Hotel and Resort',
                'city'            => 'يعفور',
                'province_id'     => $prov['ريف دمشق'] ?? null,
                'stars'           => 4,
                'price_per_night' => 110,
                'discount_price'  => null,
                'rating'          => 4.4,
                'rooms'           => 35,
                'status'          => 'active',
                'tag'             => 'منتجع',
                'image_url'       => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['منتجع هادئ', 'حدائق', 'مسبح', 'ملاعب'],
                'offer_text'      => null,
                'description'     => 'منتجع يعفور خارج دمشق. هاتف: +963113921555',
            ],

            // ── حلب ───────────────────────────────────────────────────────────
            [
                'name'            => 'Sheraton Aleppo Hotel',
                'city'            => 'حلب',
                'province_id'     => $prov['حلب'] ?? null,
                'stars'           => 5,
                'price_per_night' => 145,
                'discount_price'  => 130,
                'rating'          => 4.6,
                'rooms'           => 70,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مركز أعمال', 'قاعات اجتماعات', 'مطعم حلبي', 'توصيل مطار'],
                'offer_text'      => null,
                'description'     => 'شيراتون حلب. هاتف: +963212121111',
            ],
            [
                'name'            => 'Baron Hotel Aleppo',
                'city'            => 'حلب',
                'province_id'     => $prov['حلب'] ?? null,
                'stars'           => 3,
                'price_per_night' => 65,
                'discount_price'  => null,
                'rating'          => 4.3,
                'rooms'           => 30,
                'status'          => 'active',
                'tag'             => 'تراثي',
                'image_url'       => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['تاريخ عريق 1909م', 'ديكور كلاسيكي', 'قريب من القلعة'],
                'offer_text'      => 'أقام فيه لورنس العرب وأتاتورك',
                'description'     => 'فندق بارون التاريخي في شارع بارون بحلب.',
            ],
            [
                'name'            => 'Pullman Aleppo Hotel',
                'city'            => 'حلب',
                'province_id'     => $prov['حلب'] ?? null,
                'stars'           => 5,
                'price_per_night' => 160,
                'discount_price'  => 145,
                'rating'          => 4.5,
                'rooms'           => 80,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مسبح كبير', 'سبا', 'مطاعم متعددة', 'صالة لياقة'],
                'offer_text'      => null,
                'description'     => 'فندق بولمان الشهباء حلب. هاتف: +963212667200',
            ],
            [
                'name'            => 'Aleppo Palace Hotel',
                'city'            => 'حلب',
                'province_id'     => $prov['حلب'] ?? null,
                'stars'           => 4,
                'price_per_night' => 90,
                'discount_price'  => null,
                'rating'          => 4.0,
                'rooms'           => 35,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مركزي', 'غرف عائلية', 'مطعم'],
                'offer_text'      => null,
                'description'     => 'فندق حلب بالاس. هاتف: +963212115955',
            ],
            [
                'name'            => 'Dar Halabia Hotel',
                'city'            => 'حلب',
                'province_id'     => $prov['حلب'] ?? null,
                'stars'           => 4,
                'price_per_night' => 110,
                'discount_price'  => 95,
                'rating'          => 4.4,
                'rooms'           => 20,
                'status'          => 'active',
                'tag'             => 'تراثي',
                'image_url'       => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['باب أنطاكية', 'ديكور حلبي أصيل', 'فطور تقليدي'],
                'offer_text'      => 'في قلب المدينة القديمة',
                'description'     => 'دار حلبية في باب أنطاكية. هاتف: +963944245543',
            ],

            // ── حمص ───────────────────────────────────────────────────────────
            [
                'name'            => 'فندق سفير حمص',
                'city'            => 'حمص',
                'province_id'     => $prov['حمص'] ?? null,
                'stars'           => 5,
                'price_per_night' => 180,
                'discount_price'  => null,
                'rating'          => 4.6,
                'rooms'           => 55,
                'status'          => 'active',
                'tag'             => 'فاخر',
                'image_url'       => 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['مسبح مكشوف', 'مطعم', 'حدائق', 'نادي رياضي'],
                'offer_text'      => 'دخول النادي الرياضي مجاني',
                'description'     => 'فندق سفير الأفضل في حمص.',
            ],

            // ── حماة ──────────────────────────────────────────────────────────
            [
                'name'            => 'Afamia Alsham Hotel Hama',
                'city'            => 'حماة',
                'province_id'     => $prov['حماة'] ?? null,
                'stars'           => 5,
                'price_per_night' => 130,
                'discount_price'  => null,
                'rating'          => 4.3,
                'rooms'           => 45,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['إطلالة على نهر العاصي', 'إطلالة على النواعير', 'حدائق', 'مطعم'],
                'offer_text'      => null,
                'description'     => 'فندق أفاميا الشام المطل على نواعير حماة. هاتف: +963332525335',
            ],
            [
                'name'            => 'Orient House Hotel Hama',
                'city'            => 'حماة',
                'province_id'     => $prov['حماة'] ?? null,
                'stars'           => 4,
                'price_per_night' => 85,
                'discount_price'  => null,
                'rating'          => 4.2,
                'rooms'           => 28,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مركزي', 'مطعم شرقي', 'واي فاي'],
                'offer_text'      => null,
                'description'     => 'فندق أورينت هاوس حماة. هاتف: +963332225599',
            ],

            // ── اللاذقية ──────────────────────────────────────────────────────
            [
                'name'            => 'فندق أفاميا اللاذقية',
                'city'            => 'اللاذقية',
                'province_id'     => $prov['اللاذقية'] ?? null,
                'stars'           => 5,
                'price_per_night' => 160,
                'discount_price'  => 145,
                'rating'          => 4.6,
                'rooms'           => 75,
                'status'          => 'active',
                'tag'             => 'بحري',
                'image_url'       => 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['شاطئ خاص', 'مسابح خارجية', 'واي فاي', 'ملاعب تنس'],
                'offer_text'      => 'فطور بوفيه لشخصين مجاناً',
                'description'     => 'منتجع أفاميا الساحلي باللاذقية.',
            ],
            [
                'name'            => 'فندق غولدن بيتش اللاذقية',
                'city'            => 'اللاذقية',
                'province_id'     => $prov['اللاذقية'] ?? null,
                'stars'           => 4,
                'price_per_night' => 110,
                'discount_price'  => null,
                'rating'          => 4.3,
                'rooms'           => 40,
                'status'          => 'active',
                'tag'             => 'بحري',
                'image_url'       => 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['إطلالة بحرية', 'مسبح', 'مطعم', 'موقف'],
                'offer_text'      => null,
                'description'     => 'فندق غولدن بيتش على شاطئ اللاذقية.',
            ],

            // ── طرطوس ─────────────────────────────────────────────────────────
            [
                'name'            => 'Crowne Plaza Hotel Tartous',
                'city'            => 'طرطوس',
                'province_id'     => $prov['طرطوس'] ?? null,
                'stars'           => 5,
                'price_per_night' => 175,
                'discount_price'  => 155,
                'rating'          => 4.7,
                'rooms'           => 70,
                'status'          => 'active',
                'tag'             => 'بحري',
                'image_url'       => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['شاطئ خاص', 'مسبح كبير', 'مطاعم متعددة', 'سبا'],
                'offer_text'      => 'احجز ليلة واحصل على الثانية بنصف السعر',
                'description'     => 'كراون بلازا طرطوس على ضفاف البحر المتوسط.',
            ],

            // ── دير الزور ─────────────────────────────────────────────────────
            [
                'name'            => 'Hotel Furat Cham Palace',
                'city'            => 'دير الزور',
                'province_id'     => $prov['دير الزور'] ?? null,
                'stars'           => 4,
                'price_per_night' => 132,
                'discount_price'  => null,
                'rating'          => 4.2,
                'rooms'           => 38,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1554009975-d74653b879f1?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['إطلالة على نهر الفرات', 'مطعم شرقي', 'قاعات مناسبات'],
                'offer_text'      => null,
                'description'     => 'فندق فرات شام بالاس على نهر الفرات. هاتف: +96351225418',
            ],

            // ── السويداء ──────────────────────────────────────────────────────
            [
                'name'            => 'Castello Casole Hotel',
                'city'            => 'السويداء',
                'province_id'     => $prov['السويداء'] ?? null,
                'stars'           => 4,
                'price_per_night' => 90,
                'discount_price'  => null,
                'rating'          => 4.1,
                'rooms'           => 30,
                'status'          => 'active',
                'tag'             => 'سياحي',
                'image_url'       => 'https://images.unsplash.com/photo-1606046604972-77cc76aee944?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['طابع جبلي', 'حدائق', 'مطعم محلي'],
                'offer_text'      => null,
                'description'     => 'فندق كاستيلو كاسول في السويداء.',
            ],

            // ── الحسكة ────────────────────────────────────────────────────────
            [
                'name'            => 'Dylan Hotel Hasakah',
                'city'            => 'الحسكة',
                'province_id'     => $prov['الحسكة'] ?? null,
                'stars'           => 4,
                'price_per_night' => 110,
                'discount_price'  => null,
                'rating'          => 4.1,
                'rooms'           => 32,
                'status'          => 'active',
                'tag'             => 'أعمال',
                'image_url'       => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['إنترنت سريع', 'خدمة غرف 24 ساعة', 'موقف هادئ'],
                'offer_text'      => null,
                'description'     => 'فندق ديلان في الحسكة.',
            ],

            // ── درعا ──────────────────────────────────────────────────────────
            [
                'name'            => 'Stewart Hotel Daraa',
                'city'            => 'درعا',
                'province_id'     => $prov['درعا'] ?? null,
                'stars'           => 3,
                'price_per_night' => 60,
                'discount_price'  => null,
                'rating'          => 3.8,
                'rooms'           => 20,
                'status'          => 'active',
                'tag'             => 'اقتصادي',
                'image_url'       => 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مناسب', 'أسعار معقولة', 'خدمة جيدة'],
                'offer_text'      => null,
                'description'     => 'فندق ستيوارت في درعا.',
            ],

            // ── الرقة ─────────────────────────────────────────────────────────
            [
                'name'            => 'The May Fair Hotel Raqqa',
                'city'            => 'الرقة',
                'province_id'     => $prov['الرقة'] ?? null,
                'stars'           => 3,
                'price_per_night' => 55,
                'discount_price'  => null,
                'rating'          => 3.7,
                'rooms'           => 18,
                'status'          => 'active',
                'tag'             => 'اقتصادي',
                'image_url'       => 'https://images.unsplash.com/photo-1606046604972-77cc76aee944?auto=format&fit=crop&w=800&q=80',
                'amenities'       => ['موقع مركزي', 'أسعار مناسبة'],
                'offer_text'      => null,
                'description'     => 'فندق ماي فير في الرقة.',
            ],
        ];

        foreach ($hotels as $hotel) {
            Hotel::firstOrCreate(
                ['name' => $hotel['name'], 'city' => $hotel['city']],
                $hotel
            );
        }

        $this->command->info('✅ تم إضافة ' . count($hotels) . ' فندق سوري حقيقي');
    }
}
